import { PostCardModel } from './ui/post_card/post-card.model';
import { TabModel } from './ui/tabs/tab';

export const tabsModels: TabModel[] = [
  { id: 1, name: 'All' },
  { id: 2, name: 'My favorites' },
  { id: 3, name: 'Popular' },
];

export const postCardModels: PostCardModel[] = [
  {
    id: 1,
    image: 'https://i.pinimg.com/564x/2d/9f/67/2d9f676a7210c693186dac6c61a17ac9.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight. \nBarron and Chari put on their NASA spacesuits early Tuesday, depressurized the station’s Quest airlock, and opened the hatch to venture outside the complex. The spacewalk officially began at 8:11 a.m. EDT (1211 GMT), when the astronauts switched their suits to battery power. \nThe astronauts gathered equipment and tools before heading out to the space station’s starboard, or right-side, truss for their work. \nBarron was the lead spacewalker, designated EV1, and wore a suit marked with red stripes. Chari, designated EV2, wore a spacesuit with no stripes. \nAfter making their way to the work site, the astronauts assembled and installed brackets and struts to accommodate new solar arrays to be delivered to the space station on a future SpaceX Dragon cargo mission. The spacewalkers constructed the triangular fixture, called a modification kit and made of individual struts, to provide a mounting location for one of six new roll-out solar array wings to enhance the station’s power generation capability.',
    date: '2023-08-27',
    lesson_num: 1,
    likes_amount: 16,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 1,
  },
  {
    id: 2,
    image: 'https://i.pinimg.com/564x/90/d5/4e/90d54e958a209755a40e57e5a9e19e57.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 2,
    likes_amount: 14,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 2,
  },
  {
    id: 3,
    image: 'https://i.pinimg.com/564x/6a/d2/d9/6ad2d91c6173a208bccd951587ab4d2d.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 3,
    likes_amount: 30,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 3,
  },
  {
    id: 4,
    image: 'https://i.pinimg.com/564x/43/2b/85/432b8511c3f1c1dbcfdb74609b387c8c.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight. \nBarron and Chari put on their NASA spacesuits early Tuesday, depressurized the station’s Quest airlock, and opened the hatch to venture outside the complex. The spacewalk officially began at 8:11 a.m. EDT (1211 GMT), when the astronauts switched their suits to battery power. \nThe astronauts gathered equipment and tools before heading out to the space station’s starboard, or right-side, truss for their work. \nBarron was the lead spacewalker, designated EV1, and wore a suit marked with red stripes. Chari, designated EV2, wore a spacesuit with no stripes. \nAfter making their way to the work site, the astronauts assembled and installed brackets and struts to accommodate new solar arrays to be delivered to the space station on a future SpaceX Dragon cargo mission. The spacewalkers constructed the triangular fixture, called a modification kit and made of individual struts, to provide a mounting location for one of six new roll-out solar array wings to enhance the station’s power generation capability.',
    date: '2023-08-28',
    lesson_num: 4,
    likes_amount: 12,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 4,
  },
  {
    id: 5,
    image: 'https://i.pinimg.com/564x/f3/fa/29/f3fa2998529605eeb6d67d429c68a13b.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 5,
    likes_amount: 23,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 5,
  },
  {
    id: 6,
    image: 'https://i.pinimg.com/564x/18/f2/9f/18f29f9150439e164fbff117dad05a94.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 6,
    likes_amount: 27,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 6,
  },
  {
    id: 7,
    image: 'https://i.pinimg.com/564x/a6/74/24/a674240f62300813e1bcdfdc01aac8a1.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 7,
    likes_amount: 26,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 7,
  },
  {
    id: 8,
    image: 'https://i.pinimg.com/564x/65/c5/1d/65c51d94a696fe692539727ccbb22602.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 8,
    likes_amount: 15,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 8,
  },
  {
    id: 9,
    image: 'https://i.pinimg.com/564x/70/3c/b7/703cb7f48cab85cf06a235594b704dfd.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 9,
    likes_amount: 19,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 9,
  },
  {
    id: 10,
    image: 'https://i.pinimg.com/564x/b5/51/d4/b551d434cb5097e41f673e1e93c1c492.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 10,
    likes_amount: 22,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 10,
  },
  {
    id: 11,
    image: 'https://i.pinimg.com/564x/f3/fa/29/f3fa2998529605eeb6d67d429c68a13b.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 11,
    likes_amount: 25,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 11,
  },

];
